# Generated by Django 4.0.4 on 2022-07-03 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marcas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
                ('cuit', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Distribuidor',
                'verbose_name_plural': 'Distribuidores',
            },
        ),
        migrations.CreateModel(
            name='Distribuidores_marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre', to='distribuidores.distribuidores')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_marca', to='marcas.marcas')),
            ],
            options={
                'verbose_name': 'Distribuidores x marca',
                'verbose_name_plural': 'Distribuidores x marcas',
            },
        ),
    ]
