# Generated by Django 4.0.4 on 2022-07-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(default='', upload_to='profile_images'),
        ),
    ]
