# Generated by Django 4.0.4 on 2022-07-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='link',
            field=models.URLField(blank=True, default='-', max_length=100),
        ),
    ]
