# Generated by Django 4.0.4 on 2022-06-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
                ('cuit', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Distribuidor',
                'verbose_name_plural': 'Distribuidores',
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('descuento', models.FloatField()),
                ('novedad', models.BooleanField()),
                ('imagen', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.marcas')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.tipo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Distribuidores_Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.distribuidores')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.marcas')),
            ],
            options={
                'verbose_name': 'Distribuidores x marca',
                'verbose_name_plural': 'Distribuidores x marcas',
            },
        ),
    ]
