# Generated by Django 4.0.4 on 2022-06-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_estados_productos_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estados',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
    ]
