# Generated by Django 4.0.4 on 2022-06-26 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_estados_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='productos.estados'),
        ),
    ]
