# Generated by Django 4.0.4 on 2022-06-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_productos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
