# Generated by Django 4.0.4 on 2022-06-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_productos_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcas',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
