# Generated by Django 4.0.4 on 2022-06-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_tipo_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='estado',
        ),
    ]
