# Generated by Django 4.0.4 on 2022-07-03 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0001_initial'),
        ('categorias', '0001_initial'),
        ('productos', '0012_distribuidores_marcas_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribuidores_marcas',
            name='distribuidor',
        ),
        migrations.RemoveField(
            model_name='distribuidores_marcas',
            name='marca',
        ),
        migrations.AlterField(
            model_name='productos',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='marcas.marcas'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='categorias.tipo'),
        ),
        migrations.DeleteModel(
            name='Distribuidores',
        ),
        migrations.DeleteModel(
            name='Distribuidores_Marcas',
        ),
        migrations.DeleteModel(
            name='Marcas',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
