# Generated by Django 4.0.4 on 2022-07-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_remove_distribuidores_marcas_distribuidor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
    ]
