# Generated by Django 4.0.4 on 2022-07-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='Bienvenido a', max_length=200)),
                ('subtitulo', models.CharField(blank=True, default='Ferreteria 2010', max_length=200)),
            ],
            options={
                'verbose_name': 'Inicio Titulo',
                'verbose_name_plural': 'Inicio Titulos',
            },
        ),
    ]
