# Generated by Django 4.0.4 on 2022-07-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_extras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('puesto', models.CharField(blank=True, default='', max_length=200)),
                ('descripcion', models.CharField(blank=True, default='', max_length=400)),
            ],
            options={
                'verbose_name': 'Acerca de',
                'verbose_name_plural': 'Acerca de nosotros',
            },
        ),
    ]
